package service

import (
	"context"
	"fmt"
	"io"
	"log"
	"strings"
	"sync"

	greetv1 "example/gen/greet/v1" // generated by protoc-gen-go

	"connectrpc.com/connect"
)

type GreetServer struct{}

func (s *GreetServer) Greet(
	ctx context.Context,
	req *connect.Request[greetv1.GreetRequest],
) (*connect.Response[greetv1.GreetResponse], error) {
	log.Println("Request headers: ", req.Header())
	res := connect.NewResponse(&greetv1.GreetResponse{
		Greeting: fmt.Sprintf("Hello, %s!", req.Msg.Name),
	})
	res.Header().Set("Greet-Version", "v1")
	return res, nil
}

func (s *GreetServer) ClientGreet(
	ctx context.Context,
	stream *connect.ClientStream[greetv1.GreetRequest],
) (*connect.Response[greetv1.GreetResponse], error) {
	log.Println("ClientGreet")
	log.Println("Request headers: ", stream.RequestHeader())
	var greeting strings.Builder
	for stream.Receive() {
		g := fmt.Sprintf("Hello, %s!\n", stream.Msg().Name)
		if _, err := greeting.WriteString(g); err != nil {
			return nil, connect.NewError(connect.CodeInternal, err)
		}
	}
	if err := stream.Err(); err != nil {
		return nil, connect.NewError(connect.CodeUnknown, err)
	}
	res := connect.NewResponse(&greetv1.GreetResponse{
		Greeting: greeting.String(),
	})
	res.Header().Set("Greet-Version", "v1")
	return res, nil
}

func (s *GreetServer) ServerGreet(
	ctx context.Context,
	req *connect.Request[greetv1.GreetRequest],
	stream *connect.ServerStream[greetv1.GreetResponse]) error {
	log.Println("ServerGreet")
	log.Println("Request headers: ", req.Header())
	sysmsg := (&greetv1.GreetResponse{
		Greeting: fmt.Sprintf("server streams msgs"),
	})
	stream.Send(sysmsg)

	for i := 0; i < 5; i++ {
		res := (&greetv1.GreetResponse{
			Greeting: fmt.Sprintf("Hello, %s! %d", req.Msg.Name, i),
		})
		stream.Send(res)
	}
	return nil
}

func (s *GreetServer) BothGreet(
	ctx context.Context,
	stream *connect.BidiStream[greetv1.GreetRequest, greetv1.GreetResponse]) error {
	log.Println("BothGreet")
	log.Println("Request headers: ", stream.RequestHeader())

	ch := make(chan string, 1)
	wg := sync.WaitGroup{}
	wg.Add(2)

	// Goroutine to receive messages from the client
	go func() {
		defer wg.Done()
		for {
			req, err := stream.Receive()
			if err != nil {
				log.Printf("Failed to receive message: %v", err)
				if err == io.EOF {
					log.Println("Server closed the stream")
					break
				}
				return
			}
			ch <- req.Name
		}
	}()

	go func() {
		defer wg.Done()
		cntr := 0
		for name := range ch {
			cntr += 1
			err := stream.Send(&greetv1.GreetResponse{
				Greeting: fmt.Sprintf("Hello, %s for the %d time", name, cntr),
			})
			if err != nil {
				log.Printf("Failed to send message: %v", err)
				return
			}
		}
	}()

	wg.Wait()
	return nil
}
