package main

import (
	"net/http"

	"example/internal/service"

	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	"example/gen/greet/v1/greetv1connect" // generated by protoc-gen-connect-go
)

func main() {
	// interceptor := connect.WithInterceptors(interceptor.NewAuthInterceptor())
	greeter := &service.GreetServer{}
	mux := http.NewServeMux()
	path, handler := greetv1connect.NewGreetServiceHandler(greeter)
	mux.Handle(path, handler)
	http.ListenAndServe(
		"localhost:8080",
		// Use h2c so we can serve HTTP/2 without TLS.
		h2c.NewHandler(mux, &http2.Server{}),
	)
}
